spring:
  datasource:
    url: jdbc:postgresql://aws-1-eu-north-1.pooler.supabase.com:6543/postgres
    username: postgres.ghwfynhlsuuchfpfktql
    password: sYimVLQY7azsOliP
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-8a6i2vzseplubat2.eu.auth0.com/
          audiences: https://backlog-api

igdb:
  client-id: k2nk5jmx4g2wo9rc100mx9mdwy24mv
  client-secret: 8zgbtkf0zeqbhcqyzq8q73u8lg2mh9